CREATE DATABASE "PEOTest"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	CREATE TABLE IF NOT EXISTS public."Company"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Company" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Company"
    OWNER to postgres;
	
	CREATE TABLE IF NOT EXISTS public."Employee"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Surname" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    "Patronymic" text COLLATE pg_catalog."default",
    "Phone" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Employee" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Employee"
    OWNER to postgres;
	
	CREATE TABLE IF NOT EXISTS public."Post"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Post" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Post"
    OWNER to postgres;
	
	CREATE TABLE IF NOT EXISTS public."Subdivision"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Subdivision" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Subdivision"
    OWNER to postgres;
	
	CREATE TABLE IF NOT EXISTS public."CompEmp"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "EmployeeId" integer NOT NULL,
    "CompanyId" integer NOT NULL,
    "PostId" integer NOT NULL,
    "SubdivisionId" integer NOT NULL,
    CONSTRAINT "PK_CompEmp" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompEmp_Company_CompanyId" FOREIGN KEY ("CompanyId")
        REFERENCES public."Company" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_CompEmp_Employee_EmployeeId" FOREIGN KEY ("EmployeeId")
        REFERENCES public."Employee" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_CompEmp_Post_PostId" FOREIGN KEY ("PostId")
        REFERENCES public."Post" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_CompEmp_Subdivision_SubdivisionId" FOREIGN KEY ("SubdivisionId")
        REFERENCES public."Subdivision" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."CompEmp"
    OWNER to postgres;
-- Index: IX_CompEmp_CompanyId

-- DROP INDEX IF EXISTS public."IX_CompEmp_CompanyId";

CREATE INDEX IF NOT EXISTS "IX_CompEmp_CompanyId"
    ON public."CompEmp" USING btree
    ("CompanyId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_CompEmp_EmployeeId

-- DROP INDEX IF EXISTS public."IX_CompEmp_EmployeeId";

CREATE INDEX IF NOT EXISTS "IX_CompEmp_EmployeeId"
    ON public."CompEmp" USING btree
    ("EmployeeId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_CompEmp_PostId

-- DROP INDEX IF EXISTS public."IX_CompEmp_PostId";

CREATE INDEX IF NOT EXISTS "IX_CompEmp_PostId"
    ON public."CompEmp" USING btree
    ("PostId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_CompEmp_SubdivisionId

-- DROP INDEX IF EXISTS public."IX_CompEmp_SubdivisionId";

CREATE INDEX IF NOT EXISTS "IX_CompEmp_SubdivisionId"
    ON public."CompEmp" USING btree
    ("SubdivisionId" ASC NULLS LAST)
    TABLESPACE pg_default;